package com.umr.listycity;

import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import java.util.ArrayList;
import java.util.Arrays;

public class MainActivity extends AppCompatActivity {

    ListView cityList;
    ArrayAdapter<String> cityAdapter;
    ArrayList<String> dataList;
    EditText cityInput;
    Button addCityButton, addButton, deleteCityButton;
    int selectedPosition = -1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Make sure App starts below the Notification Bar
        // Generated by Gemini
        View mainView = findViewById(R.id.main);
        ViewCompat.setOnApplyWindowInsetsListener(mainView, (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        // Set Notification bar to Light Mode
        // Generated by Gemini
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            View decor = getWindow().getDecorView();
            decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
        }

        cityList = findViewById(R.id.city_list);
        cityInput = findViewById(R.id.city_input);
        addCityButton = findViewById(R.id.add_city_button);
        addButton = findViewById(R.id.add_button);
        deleteCityButton = findViewById(R.id.delete_city_button);

        String []cities = {"Lahore", "Karachi", "Islamabad", "Multan", "Sialkot", "Swat", "Peshawar", "Quetta"};

        dataList = new ArrayList<>();
        dataList.addAll(Arrays.asList(cities));

        // Use a custom ArrayAdapter to handle highlighting of selected city
        // Generated by Gemini
        cityAdapter = new ArrayAdapter<String>(this, R.layout.content, dataList) {
            @NonNull
            @Override
            public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent) {
                View view = super.getView(position, convertView, parent);
                if (position == selectedPosition) {
                    view.setBackgroundColor(Color.LTGRAY);
                } else {
                    view.setBackgroundColor(Color.TRANSPARENT);
                }
                return view;
            }
        };
        cityList.setAdapter(cityAdapter);

        addCityButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (cityInput.getVisibility() == View.GONE) {
                    cityInput.setVisibility(View.VISIBLE);
                    addButton.setVisibility(View.VISIBLE);
                } else {
                    cityInput.setVisibility(View.GONE);
                    addButton.setVisibility(View.GONE);
                }
            }
        });

        deleteCityButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if ((selectedPosition != -1) && (selectedPosition < dataList.size())) {
                    dataList.remove(selectedPosition);
                    cityAdapter.notifyDataSetChanged();
                    selectedPosition = -1;
                }
            }
        });

        cityList.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                if (selectedPosition == position) {
                    selectedPosition = -1;
                }
                else {
                    selectedPosition = position;
                }
                cityAdapter.notifyDataSetChanged();
            }
        });

        cityInput.setOnEditorActionListener((v, actionId, event) -> {
            // 6 is the actionId for "Done", but we check for Null/Enter key too
            String cityName = cityInput.getText().toString().trim();
            if (!cityName.isEmpty()) {
                dataList.add(cityName);
                cityAdapter.notifyDataSetChanged();
                cityInput.setText("");

                // Hide inputs just like your addButton logic
                cityInput.setVisibility(View.GONE);
                addButton.setVisibility(View.GONE);
                return true; // Indicates we handled the press
            }
            return false;
        });

        addButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String cityName = cityInput.getText().toString();
                if (!cityName.isEmpty()) {
                    dataList.add(cityName);
                    cityAdapter.notifyDataSetChanged();
                    cityInput.setText("");
                    // Optional: Hide them again after adding
                    cityInput.setVisibility(View.GONE);
                    addButton.setVisibility(View.GONE);
                }
            }
        });
    }
}
